version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requeriments/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    restart: always
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: ./requeriments/wordpress
      args:
        - WORDPRESS_DB_HOST
        - WORDPRESS_DB_NAME
        - WORDPRESS_URL
        - WORDPRESS_GUEST_USER
        - WORDPRESS_GUEST_PASSWORD
        - WORDPRESS_GUEST_EMAIL
        - WORDPRESS_DB_USER
        - WORDPRESS_DB_PASSWORD
        - WORDPRESS_ADMIN_USER
        - WORDPRESS_ADMIN_PASSWORD
        - WORDPRESS_ADMIN_EMAIL
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    networks:
      - inception-network

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: ./requeriments/mariadb
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASS
        - MYSQL_USER
        - MYSQL_PASS
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql/
    networks:
       - inception-network

volumes:
  mariadb_volume:
    external: true
  wordpress_volume:
    external: true

networks:
  inception-network:
    driver: bridge